import os
import re

# Define translation mappings
translations = {
    # ==================== Brand & System ====================
    '慧眼系统': 'Insight System',
    '慧眼平台': 'Insight Platform',
    '慧眼 系统': 'Insight System',
    '能力管理与发展系统': 'Competency Management & Development System',
    '赋能油气人才，构建专业认证体系': 'Empowering Oil & Gas Talent, Building Professional Certification',
    '石油天然气行业': 'Oil & Gas Industry',
    '专为石油天然气行业打造的全链路数字化培训与认证平台': 'A full-chain digital training and certification platform for the oil & gas industry',
    '专注石油天然气行业的全链路数字化培训与认证平台': 'A full-chain digital training and certification platform focused on oil & gas',
    '深耕石油天然气行业，提供从培训到认证的完整数字化能力管理方案': 'Deeply rooted in the oil & gas industry, providing complete digital competency management from training to certification',

    # ==================== Navigation - Main ====================
    '首页': 'Home',
    '关于我们': 'About Us',
    '新闻公告': 'News & Announcements',
    '在线学习': 'E-Learning',
    '知识矩阵': 'Knowledge Matrix',
    '技能矩阵': 'Skill Matrix',
    '经验工作坊': 'Workshop',
    '评估认证': 'Assessment & Certification',
    'Insight CA 系统': 'Insight CA System',
    'Matrix 管理': 'Matrix Management',
    '档案管理': 'Profile Management',
    '数据图表': 'Data & Reports',
    '课程成绩': 'Course Grades',
    '课程学习': 'Course Learning',
    'Insight HSSE 管理': 'Insight HSSE Management',
    'PTW 作业许可': 'PTW Work Permit',
    'HSSE Passport': 'HSSE Passport',
    '登录': 'Login',
    '注册': 'Register',
    '登 录': 'Sign In',
    '提交注册': 'Submit Registration',
    '企业注册': 'Enterprise Registration',

    # ==================== User Menu ====================
    '个人资料': 'Profile',
    '我的学习': 'My Learning',
    '我的技能': 'My Skills',
    '我的工作坊': 'My Workshops',
    '我的进度': 'My Progress',
    '我的能力矩阵': 'My Competency Matrix',
    '退出': 'Logout',
    '搜索课程、技能...': 'Search courses, skills...',
    '搜索课程...': 'Search courses...',
    '搜索新闻、公告...': 'Search news, announcements...',
    '搜索新闻标题、关键词...': 'Search news titles, keywords...',
    '搜索': 'Search',

    # ==================== Footer ====================
    '版权所有': 'All Rights Reserved',
    '隐私政策': 'Privacy Policy',
    '服务条款': 'Terms of Service',
    '网站地图': 'Sitemap',
    '帮助中心': 'Help Center',
    '常见问题': 'FAQ',
    '联系我们': 'Contact Us',
    '意见反馈': 'Feedback',
    '产品服务': 'Products & Services',
    '支持': 'Support',
    '联系方式': 'Contact Info',
    '公司地址': 'Address',
    '电子邮箱': 'Email',
    '服务热线': 'Hotline',
    '北京市朝阳区石油大厦A座18层': '18/F Petroleum Tower A, Chaoyang District, Beijing',

    # ==================== Login Page ====================
    '欢迎回来': 'Welcome Back',
    '请登录您的账户': 'Please sign in to your account',
    '用户名': 'Username',
    '密码': 'Password',
    '记住我': 'Remember me',
    '忘记密码？': 'Forgot password?',
    '还没有账号？': "Do not have an account?",
    '立即登录': 'Sign in now',
    '已有账号？': 'Already have an account?',

    # ==================== Register Page ====================
    '仅企业管理员可注册，需后台审核': 'Enterprise admins only. Requires backend approval.',
    '企业信息': 'Company Information',
    '企业名称': 'Company Name',
    '企业类型': 'Company Type',
    '请选择企业类型': 'Select company type',
    '国有企业': 'State-owned',
    '民营企业': 'Private',
    '外资企业': 'Foreign-owned',
    '合资企业': 'Joint Venture',
    '地区': 'Region',
    '请选择地区': 'Select region',
    '北京': 'Beijing',
    '天津': 'Tianjin',
    '河北': 'Hebei',
    '山西': 'Shanxi',
    '内蒙古': 'Inner Mongolia',
    '辽宁': 'Liaoning',
    '吉林': 'Jilin',
    '黑龙江': 'Heilongjiang',
    '上海': 'Shanghai',
    '江苏': 'Jiangsu',
    '浙江': 'Zhejiang',
    '安徽': 'Anhui',
    '福建': 'Fujian',
    '江西': 'Jiangxi',
    '山东': 'Shandong',
    '河南': 'Henan',
    '湖北': 'Hubei',
    '湖南': 'Hunan',
    '广东': 'Guangdong',
    '广西': 'Guangxi',
    '海南': 'Hainan',
    '重庆': 'Chongqing',
    '四川': 'Sichuan',
    '贵州': 'Guizhou',
    '云南': 'Yunnan',
    '西藏': 'Tibet',
    '陕西': 'Shaanxi',
    '甘肃': 'Gansu',
    '青海': 'Qinghai',
    '宁夏': 'Ningxia',
    '新疆': 'Xinjiang',
    '管理员信息': 'Admin Information',
    '请输入联系人姓名': 'Enter contact name',
    '请输入联系电话': 'Enter phone number',
    '请输入邮箱地址': 'Enter email address',
    '请设置用户名': 'Set username',
    '请设置密码': 'Set password',
    '请再次输入密码': 'Re-enter password',
    '请输入验证码': 'Enter verification code',
    '验证码': 'Verification Code',
    '两次输入的密码不一致，请重新输入': 'Passwords do not match. Please try again.',
    '注册申请已提交，等待后台审核': 'Registration submitted. Pending admin approval.',
    '登录功能开发中...': 'Login feature under development...',

    # ==================== Index / Hero ====================
    '油气行业专业认证平台': 'Oil & Gas Professional Certification Platform',
    '开始学习': 'Start Learning',
    '技能认证': 'Skill Certification',
    '专业课程': 'Courses',
    '认证人才': 'Certified Professionals',
    '知识学习': 'Knowledge Learning',
    '8大学科领域、149+学习单元，覆盖油气全产业链': '8 disciplines, 149+ units covering the full O&G value chain',
    '多层级技能评估与三级验证认证体系': 'Multi-level skill assessment with three-tier verification',
    '现场培训': 'On-site Training',
    '经验工作坊与线下实操培训课程': 'Workshops and hands-on training courses',

    # ==================== Index - Features ====================
    '核心优势': 'Core Strengths',
    '为什么选择慧眼系统': 'Why Insight System',
    '行业专注': 'Industry Focus',
    '专注石油天然气行业，深度理解行业培训需求与合规要求，提供针对性解决方案': 'Focused on oil & gas, deeply understanding industry training needs and compliance requirements',
    '完整体系': 'Complete System',
    '覆盖知识学习、技能认证、工作坊管理、PTW合规的全链路培训管理体系': 'End-to-end training management covering knowledge, skills, workshops, and PTW compliance',
    '专业认证': 'Professional Certification',
    '三级验证认证流程，确保技能评估的公正性与权威性，生成正式认证报告': 'Three-tier verification ensures fair and authoritative skill assessments with official reports',
    '实战导向': 'Practice Oriented',
    '结合现场实操与经验工作坊，强调实战技能培养，确保培训成果落地': 'Combining hands-on practice and workshops to ensure training results translate to real skills',

    # ==================== Index - Courses ====================
    '热门课程': 'Popular Courses',
    '推荐学科': 'Recommended Disciplines',
    '8大学科领域，从入门到精通的完整学习路径，随时随地自主学习': '8 disciplines with complete learning paths from beginner to expert',
    '健康安全环境': 'HSE',
    '井工程': 'Wells Engineering',
    '仪表与控制': 'I&C',
    '15单元': '15 Units',
    '24学时': '24 Hours',
    '21单元': '21 Units',
    '36学时': '36 Hours',
    '14单元': '14 Units',
    '28学时': '28 Hours',
    '学习进度': 'Progress',
    '未开始': 'Not Started',
    '继续学习': 'Continue',
    '人学习': ' learners',

    # ==================== Index - News ====================
    '最新动态': 'Latest News',
    '行业动态、系统更新与培训资讯': 'Industry updates, system releases, and training news',
    '系统通知': 'System Notice',
    '行业动态': 'Industry News',
    '培训资讯': 'Training News',
    '查看详情': 'View Details',

    # ==================== Index - Partners ====================
    '合作伙伴': 'Partners',
    '信任我们的企业': 'Companies That Trust Us',
    '中石油': 'CNPC',
    '中石化': 'Sinopec',
    '中海油': 'CNOOC',
    '斯伦贝谢': 'Schlumberger',
    '哈里伯顿': 'Halliburton',

    # ==================== News Page ====================
    '全部分类': 'All Categories',
    '上一页': 'Previous',
    '下一页': 'Next',
    '阅读更多': 'Read More',
    '阅读全文': 'Read Full Article',
    '相关新闻': 'Related News',
    '热门标签': 'Popular Tags',
    '相关新闻推荐': 'Related News',
    '查看全部': 'View All',
    '分享到：': 'Share to:',
    '邮件': 'Email',
    '复制链接': 'Copy Link',
    '链接已复制到剪贴板': 'Link copied to clipboard',
    '请使用微信扫一扫分享本页面': 'Please use WeChat scan to share this page',
    '4月': 'Apr',
    '3月': 'Mar',

    # ==================== News Detail ====================
    '次阅读': ' views',
    '安全培训部': 'Safety Training Dept',
    '上一篇': 'Previous Article',
    '下一篇': 'Next Article',
    '2026年4月20日': 'April 20, 2026',

    # ==================== About Page ====================
    '公司介绍': 'Company Introduction',
    '核心价值观': 'Core Values',
    '专业至上': 'Excellence First',
    '持续创新': 'Continuous Innovation',
    '客户为本': 'Customer Centric',
    '发展历程': 'Our History',
    '赋能油气人才，构建专业认证体系。': 'Empowering oil & gas talent, building professional certification.',

    # ==================== Profile Page ====================
    '联系人姓名': 'Contact Name',
    '电话': 'Phone',
    '邮箱': 'Email',
    '所属部门': 'Department',
    '职位': 'Position',
    '编辑资料': 'Edit Profile',
    '保存更改': 'Save Changes',
    '学习进度': 'Learning Progress',
    '技能档案': 'Skill Profile',
    '我的报名': 'My Registrations',
    '申诉记录': 'Appeal Records',
    '密码修改': 'Change Password',

    # ==================== Knowledge Matrix Page ====================
    '学习中': 'In Progress',
    '学习Done': 'Completed',
    '测试结果': 'Test Results',
    '我的Progress Dashboard': 'My Progress Dashboard',
    '从左侧选择一个学习单元开始学习': 'Select a learning unit from the left to start',
    '上次学习记录': 'Last Learning Record',
    '您上次停在第': 'You stopped at slide',
    '张幻灯片': '',
    '重新开始': 'Restart',
    '继续学习': 'Continue Learning',
    '完成学习': 'Complete Learning',
    '单元学习完成': 'Unit completed',
    '您已完成': 'You have completed',
    '的学习': '',
    '返回学科': 'Back to Discipline',
    '提交': 'Submit',
    '上一题': 'Previous',
    '下一题': 'Next',
    '请完成第': 'Please complete question',
    '题': '',
    '恭喜通过测试': 'Congratulations, you passed!',
    '未达到及格线（60%），请重新尝试': 'Did not pass (60% minimum). Please try again.',
    '题正确': 'correct',
    '答题回顾': 'Review',
    '正确': 'Correct',
    '错误': 'Incorrect',
    '正确答案': 'Correct answer',
    '选择正确答案': 'Choose the correct answer',
    '选择所有正确答案': 'Choose all correct answers',
    '再试一次': 'Try Again',
    '未找到匹配的学习单元': 'No matching learning units found',
    '折叠全部': 'Collapse All',
    '展开全部': 'Expand All',
    '个学习单元': ' learning units',
    'Summary 摘要': 'Summary',
    'Recent Activity 最近活动': 'Recent Activity',

    # ==================== Common UI ====================
    '编辑': 'Edit',
    '完成': 'Done',
    '资料已保存': 'Profile saved',
    '响应式': 'Responsive',
    '菜单': 'Menu',
    '切换菜单': 'Toggle Menu',
    '仅企业管理员可注册': 'Enterprise admin registration only',
    '需后台审核': 'Requires backend approval',
    '请输入企业全称': 'Enter full company name',
    'HSE 安全管理体系': 'HSE Safety Management System',
    'HSE安全管理体系': 'HSE Safety Management System',
    'Wells Engineering 钻井技术': 'Wells Engineering - Drilling Technology',
    'I&C 仪表与控制系统': 'I&C Instrumentation & Control Systems',
    'Level 2-4': 'Level 2-4',
    'Level 3-4': 'Level 3-4',
    'Level 2-3': 'Level 2-3',
    '钻井技术': 'Drilling Technology',
    '仪表与控制系统': 'Instrumentation & Control Systems',

    # ==================== Skill Matrix Page ====================
    '上传证据': 'Upload Evidence',
    '已认证技能': 'Certified Skills',
    '待审核证据': 'Pending Evidence',
    '已上传证据': 'Uploaded Evidence',
    '未读讨论': 'Unread Messages',
    '能力组合 (Portfolio)': 'Portfolios',
    '专业讨论': 'Discussion',
    '与评估师/验证员的沟通': 'Communication with Assessor/Verifier',
    '发送': 'Send',
    '待评估任务': 'Pending Tasks',
    'Completed评估': 'Completed Assessments',
    '分配候选人': 'Assigned Candidates',
    '评估通过率': 'Pass Rate',
    '候选人': 'Candidate',
    '公司': 'Company',
    'Portfolio': 'Portfolio',
    '技能单元': 'Unit',
    'Submit时间': 'Submitted',
    '操作': 'Actions',
    '待复核评估': 'Pending Review',
    '已复核通过': 'Approved',
    '已驳回': 'Rejected',
    '上传能力证据': 'Upload Evidence',
    '关联 Portfolio': 'Link Portfolio',
    '能力单元': 'Competence Unit',
    '证据文件': 'Evidence File',
    '拖拽文件到此处或点击上传': 'Drag & drop files here or click to upload',
    '描述说明': 'Description',
    'Submit证据': 'Submit Evidence',
    '能力单元明细': 'Unit Details',
    '单元名称': 'Unit Name',
    '审核中': 'Under Review',
    '上传': 'Upload',
    '已认证': 'Certified',
    '通过': 'Pass',
    '驳回': 'Reject',
    '李评估师': 'Assessor Li',
    '王验证员': 'Verifier Wang',
    '陈标准验证员': 'Standard Verifier Chen',
    '评估工作台 · Assessor Dashboard': 'Assessor Dashboard',
    '内部验证 · Internal Verification': 'Internal Verification',
    '报表与分析 · External Verifier Reports': 'External Verifier Reports',
    '已通过': 'Passed',
    '选择能力单元': 'Select Unit',
    '请选择Portfolio和能力单元': 'Please select Portfolio and unit',
    '证据已Submit，等待评估师审核': 'Evidence submitted, awaiting assessor review',
    '刘操作员': 'Operator Liu',
    '王安全员': 'Safety Officer Wang',
    '赵技术员': 'Technician Zhao',
    '评估师初审': 'Assessor Review',
    '内部验证员复核': 'Internal Verification',
    '待复核': 'Pending Review',
    '标准验证员终审': 'External Verifier Final Review',
    '已终审': 'Finalized',
    '等待中': 'Waiting',
    '复核通过': 'Review Passed',
    '已驳回至评估师': 'Returned to Assessor',
    '已应用筛选:': 'Filters applied:',
    '全部客户': 'All Customers',
    '全部区域': 'All Regions',
    '全部Portfolio': 'All Portfolios',
    '已认证优先': 'Certified first',
    '的评估已': '',
    '驳回，请填写驳回原因': 'Rejected. Please provide reason.',
    '输入消息...': 'Type a message...',
    '描述此证据如何证明您的能力...': 'Describe how this evidence demonstrates your competence...',
    '消息已发送': 'Message sent',
    '已达成': 'Achieved',
    'State': 'Status',
    '日期': 'Date',
    '能力单元': ' units',
    '已达成': 'Achieved',
    '请补充OIM-06的事件调查报告中的根本原因分析部分。': 'Please complete the root cause analysis section of the OIM-06 incident investigation report.',
    '好的，我会在本周内补充完整的5-Why分析。': 'OK, I will supplement the complete 5-Why analysis this week.',
    '收到，补充后我会尽快审核。另外PSMS-04的证据也需要更新。': 'Received. I will review promptly after the update. Also, the PSMS-04 evidence needs updating.',
    '个单元': ' units',
    'Select Portfolio': 'Select Portfolio',

    # ==================== Workshop Page ====================
    '列表视图': 'List View',
    '日历视图': 'Calendar View',
    '全部时间': 'All Time',
    '本周': 'This Week',
    '本月': 'This Month',
    '下月': 'Next Month',
    '全部地点': 'All Locations',
    '深圳': 'Shenzhen',
    '成都': 'Chengdu',
    '青岛': 'Qingdao',
    '今天': 'Today',
    '报名中': 'Open',
    '已满员': 'Full',
    '已结束': 'Ended',
    '已报名': 'Registered',
    '立即报名': 'Register Now',
    '讲师：': 'Instructor: ',
    '讲师:': 'Instructor: ',
    '待开始': 'Upcoming',
    '取消报名': 'Cancel Registration',
    '日': 'Sun',
    '一': 'Mon',
    '二': 'Tue',
    '三': 'Wed',
    '四': 'Thu',
    '五': 'Fri',
    '六': 'Sat',
    '暂无工作坊': 'No workshops',
    '工作坊': 'Workshop',
    '深海Drilling Technology实操': 'Deepwater Drilling Practice',
    'HSE应急处置演练': 'HSE Emergency Drill',
    '油气设备故障诊断': 'Equipment Fault Diagnosis',
    '井控技术培训': 'Well Control Training',
    '安全护照预审实操': 'Safety Passport Pre-audit',
    '海上平台作业规范': 'Platform Operations Standards',
    '王教授': 'Prof. Wang',
    '李专家': 'Expert Li',
    '陈工': 'Engineer Chen',
    '刘教授': 'Prof. Liu',
    '赵专家': 'Expert Zhao',
    '张专家': 'Expert Zhang',
    '确定要取消报名吗？': 'Are you sure you want to cancel registration?',
    '关键词Search...': 'Search keywords...',

    # ==================== Assessment Page ====================
    '新建评估任务': 'New Assessment Task',
    '评估工作台 - Assessor View': 'Assessor Dashboard',
    '负责技能证据的初步审核与评估判定': 'Responsible for initial review and assessment of skill evidence',
    '待评估': 'Pending',
    '今日Done': 'Completed Today',
    '通过率': 'Pass Rate',
    '三级验证流程概览': 'Three-Tier Verification Overview',
    'Assessor 初审': 'Assessor Review',
    '评估师审核证据': 'Assessor reviews evidence',
    '7项待处理': '7 pending',
    'Internal Verifier 复核': 'Internal Verification',
    '内部验证员抽查': 'IV spot check',
    '4项待复核': '4 pending review',
    'External Verifier 终审': 'External Verifier Final Review',
    '标准验证员终审确认': 'EV final confirmation',
    '2项待终审': '2 pending final review',
    '待审核': 'Pending',
    '验证中': 'In Review',
    '已验证': 'Verified',
    '待评估任务数': 'Pending Tasks',
    '已通过认证数': 'Certified',
    '验证中数量': 'In Review',
    '申诉中数量': 'Appeals',
    '评估任务': 'Assessment Tasks',
    '三级验证': 'Three-Tier Verification',
    '申诉处理': 'Appeals',
    '认证结果': 'Certification Results',
    '待评估技能证据': 'Pending Evidence Review',
    '学员信息': 'Candidate',
    '技能名称': 'Skill',
    '上传时间': 'Submitted',
    '验证State': 'Status',
    '预览': 'Preview',
    '审核证据': 'Review Evidence',
    '验证进度跟踪': 'Verification Progress',
    '反馈': 'Feedback',
    '已Submit证据': 'Submitted Evidence',
    '上传于': 'Submitted on',
    '下载': 'Download',
    '验证反馈': 'Verification Feedback',
    '反馈已发送': 'Feedback sent',
    'CAP申诉与争议处理': 'CAP Appeals & Disputes',
    '学员': 'Candidate',
    '申诉技能': 'Appeal Skill',
    '申诉理由': 'Reason',
    'CAP小组处理结果': 'CAP Team Decision',
    '处理中': 'In Progress',
    'CAP小组': 'CAP Team',
    '查看证据': 'View Evidence',
    '待分配': 'Unassigned',
    '已认证记录': 'Certified Records',
    '下载报告': 'Download Report',
    '文件预览': 'File Preview',
    '文件名称': 'File Name',
    '预览内容': 'Preview',
    '文件预览区域': 'Preview Area',
    '实际环境中将加载 PDF/视频 预览组件': 'PDF/Video preview will load in production',
    '关闭': 'Close',
    '下载文件': 'Download File',
    '评估操作': 'Assessment Action',
    '审核意见': 'Comments',
    '取消': 'Cancel',
    '确认': 'Confirm',
    '证据审核': 'Evidence Review',
    '技能名称 / 部门': 'Skill / Department',
    'Submit证据文件': 'Submit Evidence File',
    '评估师反馈': 'Assessor Feedback',
    '历史反馈': 'History',
    '驳回证据': 'Reject Evidence',
    '证据通过': 'Approve Evidence',
    '学员姓名': 'Candidate Name',
    '评估说明': 'Description',
    '创建任务': 'Create Task',
    '候选人视图 - Candidate View': 'Candidate View',
    '查看个人Skill Certification的Submit与验证进度': 'Track your skill certification submissions and verification progress',
    '待验证技能': 'Pending Skills',
    '审核中': 'In Review',
    '待Submit证据': 'Pending Submission',
    '内部复核工作台 - Internal Verifier View': 'Internal Verifier Dashboard',
    '负责评估结果的抽样复核与质量把控': 'Responsible for sampling and quality control of assessments',
    '待复核任务数': 'Pending Reviews',
    '待终审转交': 'Pending Final Review',
    '终审工作台 - External Verifier View': 'External Verifier Dashboard',
    '负责最终验证确认与认证证书签发': 'Responsible for final verification and certificate issuance',
    '待终审任务数': 'Pending Final Approvals',
    '已签发认证': 'Certificates Issued',
    '抽查复核': 'Spot Check',
    '合规审计': 'Compliance Audit',
    '已切换到:': 'Switched to: ',
    '3项等待初审': '3 pending initial review',
    '等待复核': 'Awaiting review',
    '等待终审': 'Awaiting final review',
    '通过认证': 'Approve Certification',
    '驳回申请': 'Reject Application',
    '确认通过': 'Confirm Approval',
    '确认驳回': 'Confirm Rejection',
    '请输入审核意见': 'Please enter review comments',
    '认证已通过，进入下一级验证流程': 'Certification approved, proceeding to next verification level',
    '申请已驳回，意见已记录': 'Application rejected, comments recorded',
    '请提供证据审核反馈意见': 'Please provide evidence review feedback',
    '证据审核通过，已记录反馈意见': 'Evidence approved, feedback recorded',
    '驳回时必须提供具体原因说明': 'Specific reason required for rejection',
    '证据已驳回，候选人将收到修改通知': 'Evidence rejected, candidate will be notified',
    '请填写学员姓名和技能名称': 'Please enter candidate name and skill name',
    '评估任务已创建：': 'Assessment task created: ',
    '正在生成PDF报告，请稍候...': 'Generating PDF report, please wait...',

    # Assessment Mock Data
    '李明远': 'Li Mingyuan',
    '钻井一部 / Portfolio: OIM v3': 'Drilling Dept 1 / Portfolio: OIM v3',
    '钻井操作': 'Drilling Operations',
    '王建国': 'Wang Jianguo',
    '设备维修部 / Portfolio: OP Tech L2': 'Maintenance Dept / Portfolio: OP Tech L2',
    '设备检修': 'Equipment Maintenance',
    '陈志强': 'Chen Zhiqiang',
    'HSE部 / Portfolio: PSMS v2': 'HSE Dept / Portfolio: PSMS v2',
    'HSE安全技能': 'HSE Safety Skills',
    '赵海燕': 'Zhao Haiyan',
    'Electrical Engineering部 / Portfolio: OP Tech L3': 'Electrical Engineering / Portfolio: OP Tech L3',
    '电气安全操作': 'Electrical Safety Operation',
    '刘思远': 'Liu Siyuan',
    'Wells Engineering部 / Portfolio: OIM v4': 'Wells Engineering / Portfolio: OIM v4',
    '完井技术': 'Completion Technology',
    '孙伟强': 'Sun Weiqiang',
    '质量检验': 'Quality Inspection',
    '周丽华': 'Zhou Lihua',
    '仪表自动化': 'Instrumentation & Automation',
    '吴天明': 'Wu Tianming',
    '项目管理': 'Project Management',
    '证据视频中已完整展示UT检测全过程，但审核意见称"未展示关键步骤"，与实际不符，请求重新审核。': 'The evidence video fully demonstrates the UT inspection process, but the review stated "key steps not shown." Requesting re-review.',
    '已调取原始视频，组织技术专家复核中，预计2个工作日内给出结论。': 'Original video retrieved, technical expert review in progress. Estimated 2 business days.',
    'Submit的DCS系统操作证书为国家认可机构颁发，有效期至2028年，却被判定为"证书不符合要求"，申请复核。': 'The submitted DCS operation certificate is issued by a nationally recognized body, valid until 2028, but was rejected as "non-compliant." Requesting review.',
    '经核实证书真实有效，符合认证标准。撤销原驳回决定，予以通过认证。': 'Certificate verified as authentic and compliant. Original rejection overturned, certification approved.',
    '项目管理PMP证书已在系统中备案，但本次审核未关联历史记录，导致重复驳回，请求关联后重新评估。': 'PMP certificate is on file but was not linked in this review, causing duplicate rejection. Requesting re-assessment with linkage.',
    '待CAP小组分配处理人员。': 'Awaiting CAP team assignment.',
    '持证人：': 'Certificate Holder: ',
    '通过日期：': 'Pass Date: ',
    '有效期至：': 'Valid Until: ',
    '认证等级：': 'Level: ',
    '验证路径：初审 · 复核 · 终审': 'Path: Assessor \u00b7 IV \u00b7 EV',
    '高级': 'Advanced',
    '中级': 'Intermediate',
    'Submit日期：': 'Submitted: ',
    '当前阶段：External Verifier 终审': 'Current: External Verifier Final Review',
    '待定': 'TBD',
    '等待标准验证员终审确认': 'Awaiting EV final confirmation',
    '当前阶段：Assessor 初审': 'Current: Assessor Review',
    '等待评估师初步审核': 'Awaiting assessor initial review',
    '初审 · 复核 · 终审': 'Assessor \u00b7 IV \u00b7 EV',
    'Search评估任务、认证记录...': 'Search tasks, records...',
    '添加验证反馈...': 'Add verification feedback...',
    '添加评估意见...': 'Add assessment comments...',
    '添加终审反馈...': 'Add final review feedback...',
    '请输入审核意见...': 'Enter review comments...',
    '请对Submit的证据进行评审，提供具体反馈意见...': 'Please review the submitted evidence and provide feedback...',
    '输入学员姓名...': 'Enter candidate name...',
    '输入技能名称...': 'Enter skill name...',
    '例如: OIM v3, PSMS v2...': 'e.g. OIM v3, PSMS v2...',
    '输入部门名称...': 'Enter department name...',
    '输入评估任务说明和要求...': 'Enter task description and requirements...',

    # ==================== Compliance Page ====================
    '导出报告': 'Export Report',
    '合规率': 'Compliance Rate',
    '较上月提升 2.1%': '+2.1% vs last month',
    '待整改项': 'Non-Compliances',
    '较上月减少 3 项': '-3 vs last month',
    '到期预警人数': 'Expiring Soon',
    '7 日内到期': 'Expiring within 7 days',
    '合规检查次数': 'Inspections',
    '本月累计': 'This Month',
    '合规监控': 'Compliance Monitor',
    '安全护照预审': 'Safety Passport Pre-audit',
    '各部门合规达标情况': 'Department Compliance',
    '钻Wells Engineering部': 'Wells Engineering',
    '采油生产部': 'Production Dept',
    '设备维护部': 'Maintenance Dept',
    '储运物流部': 'Logistics Dept',
    '安全环保部': 'HSE Dept',
    '外协承包商': 'Contractors',
    '合规State概览': 'Compliance Overview',
    '合规达标': 'Compliant',
    '各项检查均符合要求': 'All inspections passed',
    '限期整改': 'Rectify by Deadline',
    '需在指定时间内Done整改': 'Must complete rectification by deadline',
    '严重违规': 'Serious Violation',
    '立即停止作业并整改': 'Stop operations immediately',
    '近期合规检查记录': 'Recent Inspection Records',
    '检查项目': 'Inspection Item',
    '责任部门': 'Department',
    '检查日期': 'Date',
    '检查结果': 'Result',
    '整改期限': 'Deadline',
    '井口安全阀定期检测': 'Wellhead Safety Valve Inspection',
    '合规': 'Compliant',
    '储油罐区消防设施巡检': 'Tank Farm Fire Equipment Inspection',
    '限期整改': 'Rectify by Date',
    '承包商入场安全培训核查': 'Contractor Safety Training Audit',
    '严重违规': 'Serious Violation',
    '高压管线壁厚检测': 'High-Pressure Pipeline Thickness Test',
    '硫化氢检测仪校准': 'H2S Detector Calibration',
    'HSE 流程与 PTW/培训联动State': 'HSE Process & PTW/Training Linkage',
    '流程名称': 'Process Name',
    '关联培训': 'Linked Training',
    'PTW 联动State': 'PTW Linkage',
    '合规State': 'Status',
    '动火作业许可 (Hot Work)': 'Hot Work Permit',
    'HSE安全技能、消防应急培训': 'HSE Safety, Fire Emergency Training',
    '已联动': 'Linked',
    '查看规则': 'View Rules',
    '受限空间进入 (Confined Space)': 'Confined Space Entry',
    '受限空间作业培训、气体检测培训': 'Confined Space, Gas Detection Training',
    '高处作业许可 (Work at Height)': 'Work at Height Permit',
    '高处作业安全培训': 'Work at Height Safety Training',
    '待复核': 'Pending Review',
    '吊装作业许可 (Lifting Operation)': 'Lifting Operation Permit',
    '起重机械操作培训': 'Crane Operation Training',
    '未联动': 'Not Linked',
    '配置联动': 'Configure',
    '电气隔离作业 (Electrical Isolation)': 'Electrical Isolation',
    '电气安全操作培训': 'Electrical Safety Training',
    '挖掘作业许可 (Excavation)': 'Excavation Permit',
    '地下管线识别培训': 'Underground Pipeline ID Training',
    '不合规': 'Non-Compliant',
    '放射性作业许可 (Radiography)': 'Radiography Permit',
    '辐射防护培训': 'Radiation Protection Training',
    '临时用电许可 (Temporary Power)': 'Temporary Power Permit',
    '临时用电安全培训': 'Temporary Power Safety Training',
    '安全护照预审申请': 'Safety Passport Pre-audit Application',
    '员工姓名': 'Employee Name',
    '员工编号': 'Employee ID',
    '护照类型': 'Passport Type',
    '请选择护照类型': 'Select passport type',
    '通用安全护照': 'General Safety Passport',
    '钻井作业护照': 'Drilling Passport',
    '电气作业护照': 'Electrical Passport',
    '受限空间护照': 'Confined Space Passport',
    '高处作业护照': 'Work at Height Passport',
    '动火作业护照': 'Hot Work Passport',
    '请选择Department': 'Select Department',
    '培训Done日期': 'Training Date',
    '证书有效期至': 'Certificate Expiry',
    '备注说明': 'Remarks',
    '重置': 'Reset',
    'Submit预审': 'Submit Pre-audit',
    '安全护照预审记录': 'Pre-audit Records',
    '申请日期': 'Application Date',
    'Department': 'Department',
    '预审State': 'Status',
    '李明': 'Li Ming',
    '通过': 'Approved',
    '查看': 'View',
    '王强': 'Wang Qiang',
    '驳回': 'Rejected',
    '重新申请': 'Re-apply',
    '赵芳': 'Zhao Fang',
    '待审核': 'Pending',
    '刘洋': 'Liu Yang',
    '陈华': 'Chen Hua',
    '孙伟': 'Sun Wei',
    '安全护照详情': 'Safety Passport Details',
    '加载中...': 'Loading...',
    '合规报告正在生成中，请稍候...': 'Generating compliance report, please wait...',
    '请输入员工姓名': 'Enter employee name',
    '请输入员工编号': 'Enter employee ID',
    '请选择护照类型': 'Select passport type',
    '请选择Department': 'Select Department',
    '请选择培训Done日期': 'Select training date',
    '请选择证书有效期': 'Select certificate expiry',
    '预审申请已Submit，等待审核': 'Pre-audit application submitted, awaiting review',
    '确认通过该安全护照预审申请？': 'Confirm approval of this pre-audit application?',
    '确认驳回该安全护照预审申请？': 'Confirm rejection of this pre-audit application?',
    '已重新Submit申请，等待审核': 'Application re-submitted, awaiting review',
    'Search合规记录、HSE流程...': 'Search compliance records, HSE...',
    '请输入其他需要说明的信息...': 'Enter additional remarks...',

    # ==================== Reports Page ====================
    '导出Excel': 'Export Excel',
    '当前报表视角：': 'Report View: ',
    'CAS 能力矩阵报表': 'CAS Competency Matrix Report',
    'Competence Assurance System — 候选人 / 评估员 / 验证者多维度报表': 'Competence Assurance System \u2014 Multi-dimensional reports for candidates, assessors, and verifiers',
    '报表筛选': 'Filters',
    '全部客户 (23)': 'All Customers (23)',
    '全部区域': 'All Regions',
    '全部组合': 'All Portfolios',
    '重置': 'Reset',
    '筛选': 'Apply',
    '导出当前报表': 'Export Report',
    '培训与运营统计': 'Training & Operations',
    '培训进度总览': 'Training Progress',
    '认证通过率': 'Certification Pass Rate',
    '工作坊统计': 'Workshop Statistics',
    '合规State': 'Compliance Status',
    'PTW审批效率': 'PTW Approval Efficiency',
    '员工画像': 'Employee Profile',
    '培训进度统计': 'Training Progress Stats',
    '近30天': 'Last 30 Days',
    '近90天': 'Last 90 Days',
    '本年度': 'Year to Date',
    '各学科培训Done率': 'Completion Rate by Discipline',
    '近6个月Done人数趋势': '6-Month Completion Trend',
    '认证通过率统计': 'Certification Pass Rate Stats',
    '认证State分布': 'Certification Status Distribution',
    '各等级认证明细': 'Certification by Level',
    '技能等级': 'Skill Level',
    '总人数': 'Total',
    '通过人数': 'Passed',
    '通过率': 'Pass Rate',
    '导出认证报表': 'Export Certification Report',
    '工作坊参与统计': 'Workshop Participation',
    '海上安全操作工作坊': 'Offshore Safety Operations Workshop',
    'Drilling Technology实操工作坊': 'Drilling Technology Workshop',
    '应急响应演练工作坊': 'Emergency Response Drill',
    '设备检修技能工作坊': 'Equipment Maintenance Workshop',
    '考核Done率': 'Assessment Rate',
    '学员明细': 'Candidate Details',
    '姓名': 'Name',
    '是否参加': 'Attended',
    '考核结果': 'Result',
    '导出工作坊报表': 'Export Workshop Report',
    '数据更新时间：2026-05-29 14:30 UTC+8': 'Last updated: 2026-05-29 14:30 UTC+8',
    '共 条记录': ' records',
    '管道工程': 'Pipeline Engineering',
    '海洋工程': 'Offshore Engineering',
    '1月': 'Jan',
    '2月': 'Feb',
    '3月': 'Mar',
    '4月': 'Apr',
    '5月': 'May',
    '6月': 'Jun',
    '已通过': 'Passed',
    '待审核': 'Pending',
    '未通过': 'Failed',
    '已考核': 'Assessed',
    '未考核': 'Not Assessed',
    '李明': 'Li Ming',
    '已参加': 'Attended',
    '通过': 'Pass',
    '王芳': 'Wang Fang',
    '张伟': 'Zhang Wei',
    '未通过': 'Fail',
    '刘洋': 'Liu Yang',
    '待审核': 'Pending',
    '陈静': 'Chen Jing',
    '未参加': 'Absent',
    '赵强': 'Zhao Qiang',
    '孙丽': 'Sun Li',
    '周杰': 'Zhou Jie',
    '吴敏': 'Wu Min',
    '郑涛': 'Zheng Tao',
    '钱伟': 'Qian Wei',
    '冯雪': 'Feng Xue',
    '黄磊': 'Huang Lei',
    '林峰': 'Lin Feng',
    '徐倩': 'Xu Qian',
    '马云': 'Ma Yun',
    '朱迪': 'Zhu Di',
    '何方': 'He Fang',
    '罗丹': 'Luo Dan',
    '高翔': 'Gao Xiang',
    '正在导出数据报表，请稍候...': 'Exporting report, please wait...',
    '打开Menu': 'Open Menu',
    'Search报表、数据...': 'Search reports, data...',
    '按是否已认证排序': 'Sort by certification status',

    # ==================== Course Learn Page ====================
    '单元目录': 'Unit Outline',
    '课程进度': 'Course Progress',
    '缩小字体': 'Decrease Font Size',
    '放大字体': 'Increase Font Size',
    '暗色模式': 'Dark Mode',
    '下载课件': 'Download Materials',
    '从左侧目录选择一个单元Start Learning': 'Select a unit from the left to start learning',
    '学习统计': 'Learning Statistics',
    '学习时长': 'Study Time',
    'Completed单元': 'Completed Units',
    '测试均分': 'Avg. Test Score',
    '我的笔记': 'My Notes',
    '保存笔记': 'Save Notes',
    '疑问Submit': 'Submit Question',
    'Submit疑问给评估师': 'Submit question to assessor',
    '单元操作': 'Unit Actions',
    '标记Done': 'Mark Complete',
    '下一个单元': 'Next Unit',
    '单元未找到': 'Unit not found',
    '暂无学习内容': 'No content available',
    '已完成': 'Completed',
    '上一页': 'Previous',
    '下一页': 'Next',
    '未达到及格线（60%）': 'Below passing grade (60%)',
    'Try Again': 'Try Again',
    '返回Knowledge Matrix': 'Back to Knowledge Matrix',
    '课件下载中...（模拟）': 'Downloading materials... (simulated)',
    '笔记已保存': 'Notes saved',
    '请输入您的疑问：': 'Please enter your question:',
    '疑问已Submit至评估师': 'Question submitted to assessor',
    '单元已标记为Done': 'Unit marked as complete',
    '已是最后一个单元': 'This is the last unit',
    '记录学习要点...': 'Record key learning points...',

    # ==================== My Learning Page ====================
    '导出学习报告': 'Export Learning Report',
    '知识统计总表': 'Knowledge Summary',
    '最近活动': 'Recent Activity',
    '总体进度': 'Overall Progress',
    '共 单元': ' total units',
    'Completed单元': 'Units Completed',
    '学习统计': 'Learning Stats',
    '学科明细': 'Discipline Details',
    '编码': 'Code',
    '学科名称': 'Discipline',
    '总单元数': 'Total Units',
    'In Progress活动': 'In Progress',
    '平均测试分': 'Avg. Score',
    '知识进度': 'Progress',
    'Health Safety Environment（HSE安全）': 'Health Safety Environment (HSE)',
    'Instrumentation and Controls（仪控工程）': 'Instrumentation and Controls',
    'Process Facilities（工艺设施）': 'Process Facilities',
    'Introduction to Oil & Gas（油气概论）': 'Introduction to Oil & Gas',
    'BTEC Competences（BTEC能力）': 'BTEC Competences',
    '合计': 'Total',
    '学科进度概览': 'Discipline Progress Overview',
    '项In Progress': ' In Progress',
    '暂无活动': 'No recent activity',
    '最近学习活动': 'Recent Learning Activity',
    '活动名称': 'Activity',
    '开始日期': 'Start Date',
    '结束日期': 'End Date',
    '得分': 'Score',
    'Wells Engineering - 井控设备操作': 'Wells Engineering - Well Control Equipment Operation',
    'HSE Safety - 井场消防安全管理': 'HSE Safety - Rig Fire Safety Management',
    'Introduction to Oil & Gas - 钻井基础': 'Introduction to Oil & Gas - Drilling Fundamentals',
    'Wells Engineering - 定向Drilling Technology': 'Wells Engineering - Directional Drilling',
    'HSE Safety - 硫化氢防护与应急': 'HSE Safety - H2S Protection & Emergency',
    'I&C Engineering - PLC基础编程': 'I&C Engineering - PLC Basic Programming',
    'Mechanical Engineering - 泵阀维护与检修': 'Mechanical Engineering - Pump & Valve Maintenance',
    '学习报告正在生成中，请稍候...': 'Generating learning report, please wait...',

    # ==================== My Skills Page ====================
    '当前角色': 'Current Role',
    '能力组合': 'Portfolio',
    '整体进度': 'Overall Progress',
    '总能力单元': 'Total Units',
    '整体Done率': 'Completion Rate',
    '单元': 'Units',
    'Done进度': 'Progress',
    '单元代码': 'Code',
    '单元名称': 'Unit Name',
    '最近更新': 'Last Updated',
    '份': ' file(s)',
    '评估师': 'Assessor',
    '通用员工': 'General Staff',
    '控制室操作': 'CRO',
    '技能记录': 'Skill Records',
    '全部': 'All',
    'HSE类': 'HSE',
    'Mechanical Engineering类': 'Mechanical',
    'Wells Engineering类': 'Wells',
    'Electrical Engineering类': 'Electrical',
    '认证日期:': 'Certified: ',
    '认证日期': 'Certification Date',
    '证据材料:': 'Evidence: ',
    '证据材料': 'Evidence',
    '有效期至:': 'Valid Until: ',
    '有效期至': 'Valid Until',
    '认证进度': 'Certification Progress',
    '审核人:': 'Reviewer: ',
    '查看进度': 'View Progress',
    'Submit日期:': 'Submitted: ',
    '驳回原因:': 'Reason: ',
    '证据不足': 'Insufficient Evidence',
    '重新Submit': 'Resubmit',
    '计划日期:': 'Planned: ',
    '前置课程:': 'Prerequisite: ',
    '查看证书': 'View Certificate',
    '考核通过': 'Passed',
    '考核未通过': 'Failed',
    '重新提交': 'Resubmit',
    '取消报名': 'Cancel Registration',

    # My Skills - Skill Names
    '硫化氢防护与应急处置': 'H2S Protection & Emergency Response',
    '离心泵维护与故障诊断': 'Centrifugal Pump Maintenance & Diagnostics',
    '定向钻井轨迹控制': 'Directional Drilling Trajectory Control',
    '井场消防安全管理': 'Rig Fire Safety Management',
    '防爆电气设备检修': 'Explosion-Proof Electrical Maintenance',
    '压缩机性能测试与调试': 'Compressor Performance Testing',
    '固井作业质量控制': 'Cementing Quality Control',
    '高处作业安全管理': 'Work at Height Safety Management',
    '变电站运行维护': 'Substation Operation & Maintenance',
    '水平井完井技术': 'Horizontal Well Completion',
    '压力容器检验技术': 'Pressure Vessel Inspection',
    '受限空间作业许可': 'Confined Space Entry Permit',
    '海工平台结构完整性管理': 'Offshore Platform Structural Integrity',
    '海上设施HSE管理体系': 'Offshore Facility HSE Management',
    '应急响应与危机管理': 'Emergency Response & Crisis Management',
    '油气生产操作指挥': 'Oil & Gas Production Operations',
    '海事法规与港口国监督': 'Maritime Regulations & Port State Control',
    '重大事故情景模拟与演练': 'Major Accident Scenario Simulation',
    '工艺安全管理体系框架': 'Process Safety Management Framework',
    '工艺危害分析 (PHA)': 'Process Hazard Analysis (PHA)',
    '操作规程与安全作业程序': 'Operating Procedures & Safe Practices',
    '变更管理 (MOC)': 'Management of Change (MOC)',
    '机械完整性管理': 'Mechanical Integrity Management',
    '承包商安全管理': 'Contractor Safety Management',
    '事故调查与根因分析': 'Incident Investigation & Root Cause Analysis',
    '工艺安全关键绩效指标': 'Process Safety KPIs',
    '内部验证原则与流程': 'Internal Verification Principles & Process',
    '评估证据质量判定': 'Evidence Quality Assessment',
    '验证抽样与抽样策略': 'Verification Sampling Strategy',
    '验证报告撰写与反馈': 'Verification Report Writing & Feedback',
    '不符合项管理与纠正措施': 'Non-Conformance Management & Corrective Actions',
    '评估原则与方法论': 'Assessment Principles & Methodology',
    '评估计划制定': 'Assessment Planning',
    '证据收集与审查': 'Evidence Collection & Review',
    '评估判断与反馈沟通': 'Assessment Judgment & Feedback',
    '评估标准化与一致性': 'Assessment Standardization & Consistency',
    '多元化评估方法应用': 'Diverse Assessment Methods',
    '过程控制系统操作': 'Process Control System Operation',
    '设备启停与操作程序': 'Equipment Start-up & Shutdown Procedures',
    '仪表与警报管理': 'Instrument & Alarm Management',
    '正常操作参数监控': 'Normal Operating Parameter Monitoring',
    '异常工况处置': 'Abnormal Condition Management',
    '设备维护与润滑管理': 'Equipment Maintenance & Lubrication',
    '安全联锁与紧急停车': 'Safety Interlock & Emergency Shutdown',
    '办公室安全与消防基础': 'Office Safety & Fire Basics',
    'ERP系统基础操作': 'ERP System Basics',
    '公文写作与沟通技能': 'Business Writing & Communication',
    '信息安全与保密协议': 'Information Security & Confidentiality',
    '企业文化与职业道德': 'Corporate Culture & Ethics',
    '持续改进与创新思维': 'Continuous Improvement & Innovation',
    'DCS集散控制系统操作': 'DCS Operations',
    '报警优先级与响应策略': 'Alarm Priority & Response Strategy',
    'ESD/F&G系统操作': 'ESD/F&G System Operation',
    '交接班标准化流程': 'Shift Handover Standardization',
    '生产日志与数据记录': 'Production Logs & Data Recording',
    '高压容器操作规程': 'High-Pressure Vessel Operating Procedures',
    '旋转设备检修安全': 'Rotating Equipment Maintenance Safety',
    '管线法兰拆装作业': 'Pipeline Flange Assembly & Disassembly',
    '焊接与切割安全操作': 'Welding & Cutting Safety',
    '起重机与吊装作业': 'Crane & Lifting Operations',

    # My Skills - JS strings
    '正在跳转到「': 'Navigating to ',
    '」学习页面...': ' learning page...',
    '正在打开「': 'Opening ',
    '」重新Submit流程...': ' resubmission form...',
    '正在加载「': 'Loading ',
    '」详情...': ' details...',
    '定向钻井基础（前置课程引用）': 'Directional Drilling Fundamentals',
    '材料力学基础（前置课程引用）': 'Mechanics of Materials',
    'HSE基础安全（前置课程引用）': 'HSE Safety Fundamentals',

    # ==================== My Workshops Page ====================
    '即将开始': 'Upcoming',
    '已报名 / 人': 'Registered / capacity',
    '暂无考核结果': 'No assessment results',
    '考核通过 (分)': 'Passed (Score: ',
    '考核未通过 (分)': 'Failed (Score: ',
    '参与人数 人': 'Participants: ',
    '人': '',
    '2026年度井控技术专项培训': '2026 Well Control Technical Training',
    '华北油田培训中心 A座': 'Huabei Training Center, Building A',
    '王建国 教授': 'Prof. Wang Jianguo',
    '海上平台安全作业实操演练': 'Offshore Platform Safety Operation Drill',
    '渤海湾培训基地': 'Bohai Bay Training Base',
    '李明海 高级工程师': 'Sr. Engineer Li Minghai',
    '智能油田数字化运维技术研讨': 'Smart Oilfield Digital Operations Seminar',
    'Beijing石油管理干部学院': 'Beijing Petroleum Management Institute',
    '陈晓东 首席专家': 'Chief Expert Chen Xiaodong',
    '2026春季HSE管理体系内审员培训': '2026 Spring HSE Internal Auditor Training',
    '华北油田培训中心 B座': 'Huabei Training Center, Building B',
    '赵丽华 审核专家': 'Audit Specialist Zhao Lihua',
    '钻井液性能优化与现场应用': 'Drilling Fluid Optimization & Field Application',
    '胜利油田技术学院': 'Shengli Oilfield Technical College',
    '孙志强 技术总监': 'Technical Director Sun Zhiqiang',
    '油气储运设施完整性管理': 'Oil & Gas Storage Integrity Management',
    '管道局培训中心': 'Pipeline Bureau Training Center',
    '周海涛 高级工程师': 'Sr. Engineer Zhou Haitao',
    '2025冬季安全生产专项培训': '2025 Winter Safety Production Training',
    '吴安全 安全总监': 'Safety Director Wu Anquan',
    '确定要取消报名「': 'Are you sure you want to cancel registration for "',
    '」吗？': '"?',
    '正在加载「': 'Loading "',
    '」的详细信息...': '" details...',

    # ==================== Single character replacements (for avatars/initials) ====================
    # These must come AFTER all longer multi-character strings are handled
    '张': 'J',
    '李': 'L',
    '王': 'W',
    '陈': 'C',
    '刘': 'L',
    '赵': 'Z',
    # Brand logo single character
    'brand-logo">慧<': 'brand-logo"><i class="ri-eye-line"></i>',

    # ==================== Brand text HTML patterns (with span tags) ====================
    'brand-text">慧眼 <span>系统</span>': 'brand-text">Insight <span>System</span>',
    'brand-text">慧眼 <span style="color:#c8956c;">系统</span>': 'brand-text">Insight <span style="color:#c8956c;">System</span>',
    '.logo"><i class="ri-eye-line"></i>慧眼': '.logo"><i class="ri-eye-line"></i>Insight',
    'class="logo">慧眼': 'class="logo">Insight',
    '慧眼 V3.0 发布': 'Insight V3.0 Released',
    '慧眼 V2.0 升级': 'Insight V2.0 Upgrade',

    # ==================== Assessment remaining items ====================
    '证据': 'Evidence',
    '钻井一部': 'Drilling Dept 1',
    '设备维修部': 'Maintenance Dept',
    'HSE部': 'HSE Dept',
    'Electrical Engineering部': 'Electrical Engineering Dept',
    'Wells Engineering部': 'Wells Engineering Dept',
    'Mechanical Engineering部': 'Mechanical Engineering Dept',
    '孙': 'S',
    '周': 'Z',
    '吴': 'W',
    '钻井操作评估表_v3.pdf': 'Drilling_Ops_Assessment_v3.pdf',
    '井控操作许可证_扫描件.pdf': 'Well_Control_Permit.pdf',
    '维修记录台账_2026Q1.xlsx': 'Maintenance_Log_2026Q1.xlsx',
    '高压操作现场照片_组图.zip': 'High_Pressure_Ops_Photos.zip',
    '完井设计图纸_v2.dwg': 'Completion_Design_v2.dwg',
    'HSE培训证书.pdf': 'HSE_Training_Cert.pdf',
    '电气安全考核记录.pdf': 'Electrical_Safety_Record.pdf',
    '完井技术案例分析.pdf': 'Completion_Analysis.pdf',
    '机械检修记录.pdf': 'Mechanical_Maintenance_Record.pdf',
    '仪表校准报告.pdf': 'Instrument_Calibration_Report.pdf',
    '项目管理计划书.pdf': 'Project_Management_Plan.pdf',
    '已达标': 'Competent',

    # ==================== Workshop remaining ====================
    '参与数': 'Participants',
    '2026年': '2026 ',
    '年': '',
    '月': '',

    # ==================== Reports remaining ====================
    '共 ': 'Total: ',
    '条记录': ' records',

    # ==================== My Learning remaining ====================
    'Health Safety Environment（HSE安全）': 'Health Safety Environment (HSE)',
    'Instrumentation and Controls（仪控工程）': 'Instrumentation and Controls',
    'Process Facilities（工艺设施）': 'Process Facilities',
    'Introduction to Oil & Gas（油气概论）': 'Introduction to Oil & Gas',
    'BTEC Competences（BTEC能力）': 'BTEC Competences',
    '共 149 单元': 'Total: 149 Units',
    '（油气概论）': '',
    '（HSE安全）': '',
    '（仪控工程）': '',
    '（工艺设施）': '',
    '（BTEC能力）': '',
    '（Mechanical Engineering）': '',
    ' - 钻井基础': ' - Drilling Fundamentals',
    ' - PLC基础编程': ' - PLC Basic Programming',
    ' - 泵阀维护与检修': ' - Pump & Valve Maintenance',

    # ==================== Skill remaining ====================
    'OIM-06 事件调查': 'OIM-06 Incident Investigation',
    'OPT-03 设备操作': 'OPT-03 Equipment Operation',
    'PSMS-04 启动前审查': 'PSMS-04 Pre-Startup Review',
    'OIM-05 风险评估': 'OIM-05 Risk Assessment',
    '定向钻井基础': 'Directional Drilling Fundamentals',
    '材料力学基础': 'Mechanics of Materials',
    'HSE基础安全': 'HSE Safety Fundamentals',

    # ==================== Calendar format remaining ====================
    '${currentYear}年${currentMonth + 1}月': '${currentYear} ${currentMonth + 1}',

    # ==================== Index page - Hero ====================
    '赋能油气才<br>': 'Empowering Oil & Gas Talent<br>',
    '构建<span class="accent">Professional Certification体系</span>': 'Building <span class="accent">Professional Certification</span> Systems',
    '融合员管理、Knowledge Learning、Skill Certification、Workshop管理的全链路数字化解决方案，': 'A full-chain digital solution integrating talent management, Knowledge Learning, Skill Certification, and Workshop management, ',
    '助力企业实现从培训到认证的全流程精细化管理。': 'helping enterprises achieve refined management from training to certification.',

    # ==================== Index page - News ====================
    'Insight System V3.0 版本正式发布，新增AI智能推荐功能': 'Insight System V3.0 Released with AI Smart Recommendations',
    '本次更新引入了基于学习行为的智能课程推荐引擎，同时优化了Skill Matrix的可视化展示效果...': 'New AI-powered course recommendation engine based on learning behavior, plus improved Skill Matrix visualization...',
    '国家能源局发布新版油气行业安全培训标准': 'National Energy Administration Releases New O&G Safety Training Standards',
    '新标准对油气作业员的安全培训内容、时长及考核方式提出了更高要求，企业需在下半Done...': 'New standards raise requirements for safety training content, duration, and assessment for O&G operators...',
    'May深海Drilling TechnologyWorkshop报名开启，名额有限': 'May Deepwater Drilling Workshop Registration Now Open – Limited Spots',
    '由行业资深专家主讲的深海Drilling Technology Workshop将于May中旬举办，涵盖最新的深水Drilling Technology与...': 'Led by industry experts, the Deepwater Drilling Workshop will be held in mid-May, covering the latest deepwater technologies...',

    # ==================== Index page - Footer ====================
    '慧眼 - Competency Management & Development System，A full-chain digital training and certification platform for the oil & gas industry。': 'Insight - Competency Management & Development System. A full-chain digital training and certification platform for the oil & gas industry.',

    # ==================== News page ====================
    'Insight SystemV3.2版本升级公告': 'Insight System V3.2 Upgrade Announcement',
    '系统将于Apr25Sun凌晨2:00-6:00进行版本升级，届时部分功能可能无法正常使用。本次升级新增Skill Matrix可视化、审核流程优化等功能，请提前安排好工作。': 'System upgrade scheduled Apr 25, 2:00-6:00 AM. Some features may be unavailable. New features: Skill Matrix visualization, optimized review workflow.',
    'CNPC宣布深水油气勘探取得重大突破': 'CNPC Announces Major Deepwater O&G Exploration Breakthrough',
    '中国海洋石油总Company宣布在南海深水区域成功钻探新井，测试Sun产油气当量超千立方米，标志着我国深水油气勘探技术迈上新台阶。': 'CNOOC announces successful drilling of new deepwater well in South China Sea, with daily production exceeding 1,000 cubic meters of oil equivalent.',
    '2026 度HSE安全培训计划发布': '2026 HSE Safety Training Plan Released',
    'Year to DateHSE安全培训涵盖井控安全、海上作业安全、应急响应等Sat大模块，培训时间为May至1Jan，请各区域单位按批次组织员参加。': 'This year\'s HSE training covers well control, offshore safety, emergency response, and more. Training runs May to Dec. Regional units should organize participation in batches.',
    '国家能源局发布《油气管道完整性管理规范》修订版': 'NEA Releases Revised O&G Pipeline Integrity Management Standards',
    '新版规范增加了智能检测、数字化运维等内容，对管道全生命Z期管理提出更高要求，相关企业需在2027Jan1Sun前Done对标整改。': 'New standards add smart inspection and digital operations requirements for pipeline lifecycle management. Compliance required by Jan 1, 2027.',
    '关于FriMon劳动节放假安排的通知': 'Notice on Labor Day Holiday Arrangements',
    '根据国家节假Sun安排，FriMon劳动节放假时间为May1Sun至May5Sun，共5天。请各单位提前做好值班安排，确保安全生产。': 'Labor Day holiday: May 1-5 (5 days). Please arrange duty schedules in advance to ensure safe production.',
    '钻Wells Engineering师Advanced研修班报名开启': 'Advanced Training Program for Drilling Engineers – Registration Open',
    '由CNPC工程技术研究院主办的Advanced研修班将于Jun在Beijing举行，面向具有5以上工作经验的钻Wells Engineering师，限额50。': 'Hosted by CNPC Engineering Technology Research Institute in Beijing this June. For drilling engineers with 5+ years experience. Limited to 50 participants.',
    '全球油气行业数字化转型白皮书发布': 'Global O&G Digital Transformation White Paper Released',
    '国际石油工程师协会(SPE)联合多家能源企业发布白皮书，指出AI与数字孪生技术将在未来Fri重塑油气生产运营模式。': 'SPE and多家 energy companies release white paper on AI and digital twin technologies reshaping O&G production operations.',
    'E-Learning平台新增12门Courses': 'E-Learning Platform Adds 12 New Courses',
    'Knowledge Matrix模块新增腐蚀工程、海底管道设计、LNG工艺技术等12门课程，均已上线，Candidate可Login系统进行学习。': 'New courses added: Corrosion Engineering, Subsea Pipeline Design, LNG Process Technology, etc. Available now on the Knowledge Matrix.',
    '关于调整Skill Certification审核Z期的通知': 'Notice on Adjustment of Skill Certification Review Period',
    '为提升审核效率，自May1Sun起Skill Certification审核Z期由10个工作Sun调整为7个工作Sun，紧急申请可联系管理员加急处理。': 'Effective May 1, Skill Certification review period reduced from 10 to 7 business days. Urgent applications may contact admin for expedited processing.',
    '渤海湾盆地发现亿吨级油气田': 'Billion-Ton Oilfield Discovered in Bohai Bay Basin',
    'CNOOC宣布在渤海湾盆地渤中凹陷发现大型油气田，探明地质储量超亿吨，为近来渤海海域最大的油气发现之Mon。': 'CNOOC announces major oilfield discovery in Bohai Bay with proven reserves exceeding 100 million tons.',
    '应急演练实操培训圆满结束': 'Emergency Response Drill Training Successfully Completed',
    'Mar25Sun至27Sun，Tianjin基地举办了为期Wed天的应急响应实操培训，来自华北、华东区域的86名Candidate参加并Pass考核。': 'A 3-day emergency response training was held at Tianjin base from Mar 25-27, with 86 candidates from North and East China participating.',
    'OPEC+宣布维持现行减产政策至底': 'OPEC+ Maintains Current Production Cuts',
    'OPEC+部长级会议决定维持当前减产规模不变，国际油价应声上涨。分析士认为此举将有助于稳定全球能源市场供需平衡。': 'OPEC+ ministerial meeting decides to maintain current production cuts. Oil prices rise. Analysts say this will help stabilize global energy markets.',

    # ==================== About page ====================
    '系统商业化上线': 'Commercial Launch',
    '正式上线面向企业客户的SaaS服务平台，首批签约10家能源企业': 'SaaS platform launched for enterprise customers. First 10 energy companies signed.',
    '项目启动': 'Project Initiation',
    'Insight System研发项目启动，致力于解决油气行业培训管理痛点': 'Insight System R&D project launched to address O&G industry training management challenges.',
    '引入AI智能推荐，全面升级用户体验，服务超过50家企业客户': 'AI smart recommendations introduced, user experience upgraded, serving 50+ enterprise clients.',
    '新增Skill MatrixThree-Tier Verification、PTWCompliant联动等核心功能，Pass行业权威认证': 'Added Skill Matrix, Three-Tier Verification, PTW Compliance linkage. Passed industry certification.',

    # ==================== Register page ====================
    '联系Phone': 'Phone',

    # ==================== Assessment remaining ====================
    'Drilling Operations实操视频.mp4': 'Drilling_Operations_Demo.mp4',
    'Equipment Maintenance报告.pdf': 'Equipment_Maintenance_Report.pdf',
    '电气Actions考核记录.pdf': 'Electrical_Safety_Assessment.pdf',
    'Completion Technology案例分析.pdf': 'Completion_Technology_Analysis.pdf',
    'Drilling Operations评估表_v3.pdf': 'Drilling_Operations_Assessment_v3.pdf',
    '高压Actions现场照片_组图.zip': 'High_Pressure_Ops_Photos.zip',
    '井控Actions许可证_扫描件.pdf': 'Well_Control_Permit.pdf',
    '安全巡检记录.pdf': 'Safety_Inspection_Report.pdf',
    'UT检测完整视频.mp4': 'UT_Inspection_Full_Video.mp4',
    'DCS系统Actions证书.pdf': 'DCS_System_Certificate.pdf',
    'PMP证书_备案记录.pdf': 'PMP_Certificate_Record.pdf',
    'Passed初审。该Candidate展示了扎实的Drilling Operations能力，实操视频完整覆盖了关键作业步骤，评估表评分达到85/100。请内部验证员进行复核。': 'Passed initial review. The candidate demonstrated solid Drilling Operations capability. The practical video covers all key steps. Assessment score: 85/100. Please proceed to IV review.',
    '初审Pass，Equipment Maintenance流程规范，检测数据完整。': 'Initial review passed. Standard maintenance procedures followed, complete inspection data.',
    '内部Review Passed，评估标准执行Mon致。': 'Internal review passed. Assessment standards applied consistently.',
    '终审Pass，符合行业标准要求。认证已生效。': 'Final review passed. Meets industry standards. Certification effective.',
    '初审Pass，Electrical Safety Operation规范，考核记录完整。': 'Initial review passed. Electrical Safety Operation standards met, complete assessment records.',
    '内部Review Passed，建议终审重点关注高压Actions部分的安全Compliant性。': 'Internal review passed. Recommend EV focus on safety compliance of high-voltage operations.',
    '钻井Mon部': 'Drilling Dept 1',
    '钻井一部 / Portfolio: OIM v3': 'Drilling Dept 1 / Portfolio: OIM v3',
    'Submit于 ': 'Submitted: ',
    'Verifier Wang · 待处理': 'Verifier Wang · Pending',
    '已Approve Certification': 'Approved Certification',
    '当前阶段：External Verifier 终审': 'Current: External Verifier Final Review',
    '当前阶段：Assessor 初审': 'Current: Assessor Review',

    # ==================== My workshops remaining ====================
    'Participated (92分)': 'Participated (92 pts)',
    'Participated (88分)': 'Participated (88 pts)',
    'Participated (58分)': 'Participated (58 pts)',
    'Participated (95分)': 'Participated (95 pts)',
    'Passed (92分)': 'Passed (92 pts)',
    'Passed (88分)': 'Passed (88 pts)',
    'Failed (58分)': 'Failed (58 pts)',
    'Passed (95分)': 'Passed (95 pts)',

    # ==================== Skill remaining ====================
    '设备Actions': 'Equipment Operations',

    # ==================== Reports remaining ====================
    'logo"><i class="ri-eye-line"></i>慧眼': 'logo"><i class="ri-eye-line"></i>Insight',
}

# Sort by length descending to avoid partial replacements
translations = dict(sorted(translations.items(), key=lambda x: len(x[0]), reverse=True))

base_dir = r'C:\Users\Administrator\Desktop\网站\html-v1'

extensions = ['.html', '.css', '.js']

def process_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    original = content

    # Replace lang attribute
    content = content.replace('lang="zh-CN"', 'lang="en"')

    # Apply translations
    for cn, en in translations.items():
        if not cn.strip():
            continue
        content = content.replace(cn, en)

    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False

modified_count = 0
for root, dirs, files in os.walk(base_dir):
    for filename in files:
        if any(filename.endswith(ext) for ext in extensions):
            filepath = os.path.join(root, filename)
            if process_file(filepath):
                modified_count += 1
                print(f'Modified: {filepath}')

print(f'\nTotal files modified: {modified_count}')
